# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.3.3-node-browsers
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:9.3-alpine

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            gem install bundler
            gem update --system
            bundle install --jobs=4 --retry=3 --path vendor/bundle \
              --without development

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
        
      # Copy application configuration
      - run: cp config/application.yml.example config/application.yml

      # Database setup
      - run: bundle exec rake db:setup

      # run tests!
      - run:
          name: run tests
          command: |
            export COVERAGE=true
            make test
            bundle exec slim-lint app/views
            codeclimate-test-reporter
